services:
  beamup:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - DB_FILE_NAME=/app/db.sqlite3
      - ALLOWED_ORIGINS=http://localhost:5173
      - PROD=true
    volumes:
      - ./db.sqlite3:/app/db.sqlite3:rw
    develop:
      watch:
        - path: src/
          target: /app/src/
          action: sync+restart
        - path: drizzle/
          target: /app/drizzle/
          action: sync+restart
